// Autocomplete hints for the serial console (the trailing space marks commands that take arguments)
export const commandReference = {
  // --- device ---
  'ver': 'Show firmware version and build date',
  'board': 'Show board name',
  'reboot': 'Reboot device',
  'clkreboot': 'Reset clock to a fixed date and reboot',
  'poweroff': 'Power off device',
  'shutdown': 'Power off device',
  'clock': 'Display current time',
  'time ': 'Set time {epoch-secs} (cannot go backwards)',
  'start ota': 'Start OTA firmware update mode',
  'erase': 'Erase filesystem (factory reset, serial only)',
  'password ': 'Set new admin password',
  'powersaving': 'Show power saving state',
  'powersaving on': 'Enable power saving',
  'powersaving off': 'Disable power saving',

  // --- mesh ---
  'advert': 'Send flood advertisement packet',
  'advert.zerohop': 'Send zero-hop advertisement packet',
  'neighbors': 'List neighbours',
  'neighbor.remove ': 'Remove neighbour {pubkey-hex}',
  'discover.neighbors': 'Send node discovery request (repeater)',
  'tempradio ': 'Temporarily apply radio params {freq,bw,sf,cr,minutes}',

  // --- stats & logging ---
  'stats-core': 'Show battery, uptime, error flags and queue length (JSON)',
  'stats-radio': 'Show noise floor, RSSI, SNR and airtime (JSON)',
  'stats-packets': 'Show packet counters (JSON)',
  'clear stats': 'Reset statistics',
  'log': 'Output packet log',
  'log start': 'Start packet logging to file system',
  'log stop': 'Stop packet logging to file system',
  'log erase': 'Erase the packet logs from file system',

  // --- identity & access ---
  'get public.key': 'Get public key',
  'get prv.key': 'Get private key (serial only)',
  'set prv.key ': 'Set private key {hex} (reboot to apply)',
  'get role': 'Get node role',
  'get guest.password': 'Get guest password',
  'set guest.password ': 'Set guest password',
  'get allow.read.only': 'Get read-only login mode (room server)',
  'set allow.read.only ': 'Set read-only login mode {on|off} (room server)',
  'get acl': 'List access control entries (serial only)',
  'setperm ': 'Set node permissions {pubkey-hex} {0=remove|1=read-only|2=read-write|3=admin}',

  // --- node ---
  'get name': 'Get advertisement name',
  'set name ': 'Set advertisement name',
  'get lat': 'Get the advertisement map latitude',
  'set lat ': 'Set the advertisement map latitude',
  'get lon': 'Get the advertisement map longitude',
  'set lon ': 'Set the advertisement map longitude',
  'get owner.info': 'Get owner info',
  'set owner.info ': 'Set owner info (use | for new line, max 119 bytes)',
  'get repeat': 'Get repeater mode',
  'set repeat ': 'Set repeater mode {on|off}',

  // --- radio ---
  'get radio': 'Get radio params (freq,bw,sf,cr)',
  'set radio ': 'Set radio params {freq,bw,sf,cr} (reboot to apply)',
  'get freq': 'Get frequency (MHz)',
  'set freq ': 'Set frequency {MHz} (reboot to apply)',
  'get tx': 'Get Tx power (dBm)',
  'set tx ': 'Set Tx power {dBm}',
  'get af': 'Get air-time factor',
  'set af ': 'Set air-time factor',
  'get dutycycle': 'Get duty cycle (%)',
  'set dutycycle ': 'Set duty cycle {1-100 %}',
  'get cad': 'Get channel activity detection',
  'set cad ': 'Set channel activity detection {on|off}',
  'get int.thresh': 'Get interference threshold',
  'set int.thresh ': 'Set interference threshold {0-255}',
  'get radio.rxgain': 'Get RX boosted gain',
  'set radio.rxgain ': 'Set RX boosted gain {on|off}',
  'get rxdelay': 'Get RX delay base',
  'set rxdelay ': 'Set RX delay base {0-20}',
  'get txdelay': 'Get flood TX delay factor',
  'set txdelay ': 'Set flood TX delay factor {0-2}',
  'get direct.txdelay': 'Get direct TX delay factor',
  'set direct.txdelay ': 'Set direct TX delay factor {0-2}',
  'get agc.reset.interval': 'Get AGC reset interval (secs)',
  'set agc.reset.interval ': 'Set AGC reset interval {secs, rounded to 4}',
  'get path.hash.mode': 'Get path hash mode',
  'set path.hash.mode ': 'Set path hash mode {0=1-byte|1=2-byte|2=3-byte}',
  'get multi.acks': 'Get multi-ACK mode',
  'set multi.acks ': 'Set multi-ACK mode {0|1}',
  'get extra.sf': 'Get extra spreading factors (LR2021)',
  'set extra.sf ': 'Set extra spreading factors {sf,sf,sf} (LR2021)',
  'get adc.multiplier': 'Get battery ADC multiplier',
  'set adc.multiplier ': 'Set battery ADC multiplier {0=board default}',

  // --- routing & advertising ---
  'get advert.interval': 'Get local advert interval (minutes)',
  'set advert.interval ': 'Set local advert interval {60-240 minutes, 0=off}',
  'get flood.advert.interval': 'Get flood advert interval (hours)',
  'set flood.advert.interval ': 'Set flood advert interval {3-168 hours, 0=off}',
  'get flood.max': 'Get max flood hops',
  'set flood.max ': 'Set max flood hops {0-64}',
  'get flood.max.unscoped': 'Get max flood hops for unscoped packets',
  'set flood.max.unscoped ': 'Set max flood hops for unscoped packets {0-64}',
  'get flood.max.advert': 'Get max flood hops for adverts',
  'set flood.max.advert ': 'Set max flood hops for adverts {0-64}',
  'get loop.detect': 'Get loop detection mode',
  'set loop.detect ': 'Set loop detection mode {off|minimal|moderate|strict}',

  // --- regions ---
  'region': 'Show region tree',
  'region def ': 'Define regions {name[|jump-to] ...}',
  'region load': 'Bulk-import region tree (one indented region per line, blank line commits)',
  'region save': 'Save regions to file system',
  'region put ': 'Add or re-parent region {name} [parent]',
  'region remove ': 'Remove region {name} (must have no children)',
  'region get ': 'Show region {name}',
  'region list ': 'List regions {allowed|denied}',
  'region allowf ': 'Allow flood for region {name}',
  'region denyf ': 'Deny flood for region {name}',
  'region home': 'Show home region',
  'region home ': 'Set home region {name}',
  'region default': 'Show default region',
  'region default ': 'Set default region {name|<null>}',

  // --- gps ---
  'gps': 'Show GPS status',
  'gps on': 'Enable GPS',
  'gps off': 'Disable GPS',
  'gps sync': 'Sync clock from GPS',
  'gps setloc': 'Set advert location from GPS fix',
  'gps advert': 'Show GPS advert location policy',
  'gps advert ': 'Set GPS advert location policy {none|share|prefs}',

  // --- sensors ---
  'sensor list': 'List sensor settings [start-index]',
  'sensor get ': 'Get sensor setting {key}',
  'sensor set ': 'Set sensor setting {key} {value}',

  // --- bridge ---
  'get bridge.type': 'Get bridge type (rs232|espnow|none)',
  'get bridge.enabled': 'Get bridge state',
  'set bridge.enabled ': 'Set bridge state {on|off}',
  'get bridge.delay': 'Get bridge delay (ms)',
  'set bridge.delay ': 'Set bridge delay {0-10000 ms}',
  'get bridge.source': 'Get bridge packet source',
  'set bridge.source ': 'Set bridge packet source {tx|rx}',
  'get bridge.baud': 'Get RS232 bridge baud rate',
  'set bridge.baud ': 'Set RS232 bridge baud rate {9600-115200}',
  'get bridge.channel': 'Get ESP-NOW bridge channel',
  'set bridge.channel ': 'Set ESP-NOW bridge channel {1-14}',
  'get bridge.secret': 'Get ESP-NOW bridge secret',
  'set bridge.secret ': 'Set ESP-NOW bridge secret',

  // --- power / platform ---
  'get bootloader.ver': 'Get bootloader version (nRF52)',
  'get pwrmgt.support': 'Get power management support',
  'get pwrmgt.source': 'Get power source (external|battery)',
  'get pwrmgt.bootreason': 'Get last reset and shutdown reason',
  'get pwrmgt.bootmv': 'Get boot voltage (mV)',

  // --- MQTT shared ---
  'get mqtt.origin': 'Get MQTT origin name',
  'set mqtt.origin ': 'Set MQTT origin name',
  'get mqtt.iata': 'Get IATA code',
  'set mqtt.iata ': 'Set IATA code (auto-uppercased)',
  'get mqtt.status': 'Get MQTT connection status per slot',
  'get mqtt.presets': 'List available MQTT presets',
  'get mqtt.presets ': 'List MQTT presets from index {start}',
  'get mqtt.packets': 'Get packet message setting (on/off)',
  'set mqtt.packets ': 'Enable/disable packet messages {on|off}',
  'get mqtt.raw': 'Get raw message setting (on/off)',
  'set mqtt.raw ': 'Enable/disable raw messages {on|off}',
  'get mqtt.rx': 'Get RX packet uplinking setting (on/off)',
  'set mqtt.rx ': 'Enable/disable RX packet uplinking {on|off}',
  'get mqtt.tx': 'Get TX packet uplinking setting (on/off/advert)',
  'set mqtt.tx ': 'Set TX packet uplinking {on|off|advert}',
  'get mqtt.interval': 'Get status publish interval (minutes)',
  'set mqtt.interval ': 'Set status publish interval {1-60 minutes}',
  'get mqtt.owner': 'Get owner public key',
  'set mqtt.owner ': 'Set owner public key {64-hex-char-key}',
  'get mqtt.email': 'Get owner email address',
  'set mqtt.email ': 'Set owner email address',

  // --- MQTT slots ---
  'get mqtt1.preset': 'Get slot 1 preset name',
  'set mqtt1.preset ': 'Set slot 1 preset {analyzer-us|analyzer-eu|meshmapper|meshrank|waev|meshomatic|cascadiamesh|tennmesh|nashmesh|chimesh|meshat.se|eastidahomesh|coloradomesh|custom|none}',
  'get mqtt1.server': 'Get slot 1 server hostname',
  'set mqtt1.server ': 'Set slot 1 custom server hostname',
  'get mqtt1.port': 'Get slot 1 server port',
  'set mqtt1.port ': 'Set slot 1 custom server port {1-65535}',
  'get mqtt1.username': 'Get slot 1 username',
  'set mqtt1.username ': 'Set slot 1 custom username',
  'get mqtt1.password': 'Get slot 1 password',
  'set mqtt1.password ': 'Set slot 1 custom password',
  'get mqtt1.token': 'Get slot 1 per-slot token',
  'set mqtt1.token ': 'Set slot 1 token (required for meshrank preset)',
  'get mqtt1.topic': 'Get slot 1 custom topic template',
  'set mqtt1.topic ': 'Set slot 1 custom topic template e.g. {iata}/{device}/{type}',
  'get mqtt1.audience': 'Get slot 1 JWT audience',
  'set mqtt1.audience ': 'Set slot 1 JWT audience (enables Ed25519 auth; omit value to clear)',
  'get mqtt2.preset': 'Get slot 2 preset name',
  'set mqtt2.preset ': 'Set slot 2 preset {analyzer-us|analyzer-eu|meshmapper|meshrank|waev|meshomatic|cascadiamesh|tennmesh|nashmesh|chimesh|meshat.se|eastidahomesh|coloradomesh|custom|none}',
  'get mqtt2.server': 'Get slot 2 server hostname',
  'set mqtt2.server ': 'Set slot 2 custom server hostname',
  'get mqtt2.port': 'Get slot 2 server port',
  'set mqtt2.port ': 'Set slot 2 custom server port {1-65535}',
  'get mqtt2.username': 'Get slot 2 username',
  'set mqtt2.username ': 'Set slot 2 custom username',
  'get mqtt2.password': 'Get slot 2 password',
  'set mqtt2.password ': 'Set slot 2 custom password',
  'get mqtt2.token': 'Get slot 2 per-slot token',
  'set mqtt2.token ': 'Set slot 2 token (required for meshrank preset)',
  'get mqtt2.topic': 'Get slot 2 custom topic template',
  'set mqtt2.topic ': 'Set slot 2 custom topic template e.g. {iata}/{device}/{type}',
  'get mqtt2.audience': 'Get slot 2 JWT audience',
  'set mqtt2.audience ': 'Set slot 2 JWT audience (enables Ed25519 auth; omit value to clear)',
  'get mqtt3.preset': 'Get slot 3 preset name',
  'set mqtt3.preset ': 'Set slot 3 preset {analyzer-us|analyzer-eu|meshmapper|meshrank|waev|meshomatic|cascadiamesh|tennmesh|nashmesh|chimesh|meshat.se|eastidahomesh|coloradomesh|custom|none}',
  'get mqtt3.server': 'Get slot 3 server hostname',
  'set mqtt3.server ': 'Set slot 3 custom server hostname',
  'get mqtt3.port': 'Get slot 3 server port',
  'set mqtt3.port ': 'Set slot 3 custom server port {1-65535}',
  'get mqtt3.username': 'Get slot 3 username',
  'set mqtt3.username ': 'Set slot 3 custom username',
  'get mqtt3.password': 'Get slot 3 password',
  'set mqtt3.password ': 'Set slot 3 custom password',
  'get mqtt3.token': 'Get slot 3 per-slot token',
  'set mqtt3.token ': 'Set slot 3 token (required for meshrank preset)',
  'get mqtt3.topic': 'Get slot 3 custom topic template',
  'set mqtt3.topic ': 'Set slot 3 custom topic template e.g. {iata}/{device}/{type}',
  'get mqtt3.audience': 'Get slot 3 JWT audience',
  'set mqtt3.audience ': 'Set slot 3 JWT audience (enables Ed25519 auth; omit value to clear)',
  'get mqtt4.preset': 'Get slot 4 preset name',
  'set mqtt4.preset ': 'Set slot 4 preset {analyzer-us|analyzer-eu|meshmapper|meshrank|waev|meshomatic|cascadiamesh|tennmesh|nashmesh|chimesh|meshat.se|eastidahomesh|coloradomesh|custom|none}',
  'get mqtt4.server': 'Get slot 4 server hostname',
  'set mqtt4.server ': 'Set slot 4 custom server hostname',
  'get mqtt4.port': 'Get slot 4 server port',
  'set mqtt4.port ': 'Set slot 4 custom server port {1-65535}',
  'get mqtt4.username': 'Get slot 4 username',
  'set mqtt4.username ': 'Set slot 4 custom username',
  'get mqtt4.password': 'Get slot 4 password',
  'set mqtt4.password ': 'Set slot 4 custom password',
  'get mqtt4.token': 'Get slot 4 per-slot token',
  'set mqtt4.token ': 'Set slot 4 token (required for meshrank preset)',
  'get mqtt4.topic': 'Get slot 4 custom topic template',
  'set mqtt4.topic ': 'Set slot 4 custom topic template e.g. {iata}/{device}/{type}',
  'get mqtt4.audience': 'Get slot 4 JWT audience',
  'set mqtt4.audience ': 'Set slot 4 JWT audience (enables Ed25519 auth; omit value to clear)',
  'get mqtt5.preset': 'Get slot 5 preset name',
  'set mqtt5.preset ': 'Set slot 5 preset {analyzer-us|analyzer-eu|meshmapper|meshrank|waev|meshomatic|cascadiamesh|tennmesh|nashmesh|chimesh|meshat.se|eastidahomesh|coloradomesh|custom|none}',
  'get mqtt5.server': 'Get slot 5 server hostname',
  'set mqtt5.server ': 'Set slot 5 custom server hostname',
  'get mqtt5.port': 'Get slot 5 server port',
  'set mqtt5.port ': 'Set slot 5 custom server port {1-65535}',
  'get mqtt5.username': 'Get slot 5 username',
  'set mqtt5.username ': 'Set slot 5 custom username',
  'get mqtt5.password': 'Get slot 5 password',
  'set mqtt5.password ': 'Set slot 5 custom password',
  'get mqtt5.token': 'Get slot 5 per-slot token',
  'set mqtt5.token ': 'Set slot 5 token (required for meshrank preset)',
  'get mqtt5.topic': 'Get slot 5 custom topic template',
  'set mqtt5.topic ': 'Set slot 5 custom topic template e.g. {iata}/{device}/{type}',
  'get mqtt5.audience': 'Get slot 5 JWT audience',
  'set mqtt5.audience ': 'Set slot 5 JWT audience (enables Ed25519 auth; omit value to clear)',
  'get mqtt6.preset': 'Get slot 6 preset name',
  'set mqtt6.preset ': 'Set slot 6 preset {analyzer-us|analyzer-eu|meshmapper|meshrank|waev|meshomatic|cascadiamesh|tennmesh|nashmesh|chimesh|meshat.se|eastidahomesh|coloradomesh|custom|none}',
  'get mqtt6.server': 'Get slot 6 server hostname',
  'set mqtt6.server ': 'Set slot 6 custom server hostname',
  'get mqtt6.port': 'Get slot 6 server port',
  'set mqtt6.port ': 'Set slot 6 custom server port {1-65535}',
  'get mqtt6.username': 'Get slot 6 username',
  'set mqtt6.username ': 'Set slot 6 custom username',
  'get mqtt6.password': 'Get slot 6 password',
  'set mqtt6.password ': 'Set slot 6 custom password',
  'get mqtt6.token': 'Get slot 6 per-slot token',
  'set mqtt6.token ': 'Set slot 6 token (required for meshrank preset)',
  'get mqtt6.topic': 'Get slot 6 custom topic template',
  'set mqtt6.topic ': 'Set slot 6 custom topic template e.g. {iata}/{device}/{type}',
  'get mqtt6.audience': 'Get slot 6 JWT audience',
  'set mqtt6.audience ': 'Set slot 6 JWT audience (enables Ed25519 auth; omit value to clear)',

  // --- WiFi ---
  'get wifi.ssid': 'Get WiFi SSID',
  'set wifi.ssid ': 'Set WiFi SSID (spaces allowed, no quotes)',
  'get wifi.pwd': 'Get WiFi password',
  'set wifi.pwd ': 'Set WiFi password (spaces allowed; use trailing space only for open networks)',
  'get wifi.status': 'Get WiFi connection status, IP, RSSI, and uptime',
  'get wifi.powersave': 'Get WiFi power save mode (none/min/max)',
  'set wifi.powersave ': 'Set WiFi power save mode {none|min|max}',

  // --- Timezone ---
  'get timezone': 'Get timezone string e.g. America/Los_Angeles',
  'set timezone ': 'Set timezone {IANA string|abbreviation|UTC offset}',
  'get timezone.offset': 'Get timezone offset in hours',
  'set timezone.offset ': 'Set timezone offset in hours {-12 to +14}',

  // --- SNMP ---
  'get snmp': 'Get SNMP agent status (on/off)',
  'set snmp ': 'Enable/disable SNMP agent {on|off} (restart required)',
  'get snmp.community': 'Get SNMP community string',
  'set snmp.community ': 'Set SNMP community string (restart required)',
};
